// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orchestration.Data;

#nullable disable

namespace Orchestration.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119121826_NewSqlServer")]
    partial class NewSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orchestration.Data.Entities.AIModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AvgLatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerToken")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Regions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SuccessRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("AIModels");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            ApiEndpoint = "https://api.meta.com/v1/llama3",
                            ApiKey = "",
                            AvgLatencyMs = 135,
                            Capabilities = "text, reasoning",
                            CostPerToken = 0.006m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "LLaMA 3",
                            Priority = 1,
                            ProviderId = 5,
                            Regions = "us-east, eu-west",
                            SuccessRate = 0.93m,
                            TaskType = "reasoning",
                            Version = "v3.0"
                        },
                        new
                        {
                            Id = 7,
                            ApiEndpoint = "https://api.mistral.ai/v1/mistral7b",
                            ApiKey = "",
                            AvgLatencyMs = 125,
                            Capabilities = "lightweight text generation",
                            CostPerToken = 0.003m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Mistral 7B",
                            Priority = 1,
                            ProviderId = 6,
                            Regions = "eu-west",
                            SuccessRate = 0.91m,
                            TaskType = "reasoning",
                            Version = "7B"
                        },
                        new
                        {
                            Id = 8,
                            ApiEndpoint = "https://api.mistral.ai/v1/mixtral",
                            ApiKey = "",
                            AvgLatencyMs = 145,
                            Capabilities = "mixture of experts",
                            CostPerToken = 0.004m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Mixtral 8x7B",
                            Priority = 2,
                            ProviderId = 6,
                            Regions = "eu-west",
                            SuccessRate = 0.90m,
                            TaskType = "reasoning",
                            Version = "8x7B"
                        },
                        new
                        {
                            Id = 9,
                            ApiEndpoint = "https://api.huggingface.co/v1/bloom",
                            ApiKey = "",
                            AvgLatencyMs = 170,
                            Capabilities = "multilingual text generation",
                            CostPerToken = 0.005m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "BLOOM",
                            Priority = 1,
                            ProviderId = 4,
                            Regions = "global",
                            SuccessRate = 0.89m,
                            TaskType = "reasoning",
                            Version = "v1.0"
                        },
                        new
                        {
                            Id = 10,
                            ApiEndpoint = "https://api.huggingface.co/v1/falcon",
                            ApiKey = "",
                            AvgLatencyMs = 165,
                            Capabilities = "text generation",
                            CostPerToken = 0.004m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Falcon",
                            Priority = 2,
                            ProviderId = 4,
                            Regions = "global",
                            SuccessRate = 0.88m,
                            TaskType = "reasoning",
                            Version = "v1.0"
                        },
                        new
                        {
                            Id = 11,
                            ApiEndpoint = "https://api.cohere.ai/v1/command-r-plus",
                            ApiKey = "",
                            AvgLatencyMs = 155,
                            Capabilities = "RAG, text generation",
                            CostPerToken = 0.015m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Command R+",
                            Priority = 1,
                            ProviderId = 7,
                            Regions = "us-east, eu-west",
                            SuccessRate = 0.92m,
                            TaskType = "retrieval-augmented",
                            Version = "R+"
                        },
                        new
                        {
                            Id = 12,
                            ApiEndpoint = "https://api.ai21.com/v1/jurassic2",
                            ApiKey = "",
                            AvgLatencyMs = 150,
                            Capabilities = "text generation",
                            CostPerToken = 0.012m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Jurassic-2",
                            Priority = 1,
                            ProviderId = 8,
                            Regions = "us-east, eu-west",
                            SuccessRate = 0.91m,
                            TaskType = "text-generation",
                            Version = "v2.0"
                        });
                });

            modelBuilder.Entity("Orchestration.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArbitrationReasoning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ComplianceTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.OrchestrationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChosenModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrchestrationLogs");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceTags")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            ComplianceTags = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Meta AI",
                            TrustLevel = 1,
                            Vendor = "Meta",
                            Website = "https://ai.meta.com"
                        },
                        new
                        {
                            Id = 6,
                            ComplianceTags = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mistral AI",
                            TrustLevel = 1,
                            Vendor = "Mistral",
                            Website = "https://mistral.ai"
                        },
                        new
                        {
                            Id = 4,
                            ComplianceTags = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "HuggingFace",
                            TrustLevel = 1,
                            Vendor = "HuggingFace",
                            Website = "https://huggingface.co"
                        },
                        new
                        {
                            Id = 7,
                            ComplianceTags = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Cohere",
                            TrustLevel = 1,
                            Vendor = "Cohere",
                            Website = "https://cohere.com"
                        },
                        new
                        {
                            Id = 8,
                            ComplianceTags = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "AI21 Labs",
                            TrustLevel = 1,
                            Vendor = "AI21 Labs",
                            Website = "https://ai21.com"
                        });
                });

            modelBuilder.Entity("Orchestration.Data.Entities.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChosenModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FailoverFlag")
                        .HasColumnType("bit");

                    b.Property<int>("Latency")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdOrAPIKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.AIModel", b =>
                {
                    b.HasOne("Orchestration.Data.Entities.Provider", "Provider")
                        .WithMany("AIModels")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.Provider", b =>
                {
                    b.Navigation("AIModels");
                });
#pragma warning restore 612, 618
        }
    }
}
