// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orchestration.Data;

#nullable disable

namespace Orchestration.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118085105_EnhancedAIModelAndProviderEntities")]
    partial class EnhancedAIModelAndProviderEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orchestration.Data.Entities.AIModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AvgLatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerToken")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Regions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SuccessRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("AIModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiEndpoint = "https://api.openai.com/v1/gpt5",
                            ApiKey = "",
                            AvgLatencyMs = 120,
                            Capabilities = "text, reasoning, multimodal",
                            CostPerToken = 0.020m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "GPT-5",
                            Priority = 1,
                            ProviderId = 1,
                            Regions = "us-east, eu-west",
                            SuccessRate = 0.98m,
                            TaskType = "reasoning",
                            Version = "v5.0"
                        },
                        new
                        {
                            Id = 2,
                            ApiEndpoint = "https://api.anthropic.com/v1/claude",
                            ApiKey = "",
                            AvgLatencyMs = 150,
                            Capabilities = "text, summarization, reasoning",
                            CostPerToken = 0.018m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Claude 4.1",
                            Priority = 1,
                            ProviderId = 2,
                            Regions = "us-east, eu-west",
                            SuccessRate = 0.97m,
                            TaskType = "summarization",
                            Version = "v4.1"
                        },
                        new
                        {
                            Id = 3,
                            ApiEndpoint = "https://api.google.com/v1/gemini",
                            ApiKey = "",
                            AvgLatencyMs = 140,
                            Capabilities = "text, multimodal",
                            CostPerToken = 0.017m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Gemini 1.5",
                            Priority = 1,
                            ProviderId = 3,
                            Regions = "us-central, eu-west",
                            SuccessRate = 0.96m,
                            TaskType = "reasoning",
                            Version = "v1.5"
                        },
                        new
                        {
                            Id = 4,
                            ApiEndpoint = "https://api.microsoft.com/v1/copilot",
                            ApiKey = "",
                            AvgLatencyMs = 130,
                            Capabilities = "text, reasoning, productivity",
                            CostPerToken = 0.019m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Copilot",
                            Priority = 1,
                            ProviderId = 11,
                            Regions = "us-east, eu-west",
                            SuccessRate = 0.95m,
                            TaskType = "productivity",
                            Version = "2025"
                        },
                        new
                        {
                            Id = 5,
                            ApiEndpoint = "https://api.alibaba.com/v1/qwen3",
                            ApiKey = "",
                            AvgLatencyMs = 160,
                            Capabilities = "multilingual text generation",
                            CostPerToken = 0.008m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HealthStatus = 0,
                            IsActive = true,
                            Name = "Qwen 3",
                            Priority = 1,
                            ProviderId = 10,
                            Regions = "asia-east, eu-west",
                            SuccessRate = 0.94m,
                            TaskType = "multilingual",
                            Version = "v3.0"
                        });
                });

            modelBuilder.Entity("Orchestration.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArbitrationReasoning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ComplianceTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.OrchestrationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChosenModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrchestrationLogs");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceTags")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplianceTags = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "OpenAI",
                            TrustLevel = 0,
                            Vendor = "OpenAI",
                            Website = "https://openai.com"
                        },
                        new
                        {
                            Id = 2,
                            ComplianceTags = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Anthropic",
                            TrustLevel = 0,
                            Vendor = "Anthropic",
                            Website = "https://anthropic.com"
                        },
                        new
                        {
                            Id = 3,
                            ComplianceTags = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Google DeepMind",
                            TrustLevel = 0,
                            Vendor = "Google",
                            Website = "https://deepmind.google"
                        },
                        new
                        {
                            Id = 11,
                            ComplianceTags = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Microsoft Azure AI",
                            TrustLevel = 0,
                            Vendor = "Microsoft",
                            Website = "https://azure.microsoft.com/ai"
                        },
                        new
                        {
                            Id = 10,
                            ComplianceTags = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Alibaba DAMO Academy",
                            TrustLevel = 0,
                            Vendor = "Alibaba",
                            Website = "https://damo.alibaba.com"
                        });
                });

            modelBuilder.Entity("Orchestration.Data.Entities.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChosenModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FailoverFlag")
                        .HasColumnType("bit");

                    b.Property<int>("Latency")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdOrAPIKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.AIModel", b =>
                {
                    b.HasOne("Orchestration.Data.Entities.Provider", "Provider")
                        .WithMany("AIModels")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Orchestration.Data.Entities.Provider", b =>
                {
                    b.Navigation("AIModels");
                });
#pragma warning restore 612, 618
        }
    }
}
